### ISSUE TITLE
Point Light Bug?

### ISSUE THREAD

**Issue by scorpius** [JiayinCao/SORT#117]
The point light seems to have trouble with surfaces that are completely vertical or horizontal. I changed it to a spotlight in the bottom render.

![untitled](https://user-images.githubusercontent.com/82129/80654137-a2651280-8a49-11ea-8ad7-cdf2fd3ef92a.jpg)
![untitled1](https://user-images.githubusercontent.com/82129/80654145-a42ed600-8a49-11ea-9246-164302ca2012.jpg)

**Comment by JiayinCao** [comment]
Thanks for reporting this.

I'll take a look when I find time.

**Comment by JiayinCao** [comment]
This is because shadow ray intersects with the geometry that it leaves from.
Fixed in b69bb26c455dc3194256a1ce84f3c4624bd512e6
