### ISSUE TITLE
Support Sub-surface scatering

### ISSUE THREAD

**Issue by JiayinCao** [JiayinCao/SORT#85]

**Comment by JerryCao1985** [comment]
Done
- First iteration that works.  36fefc11fefd2850a53ba52ac78ef10c6dadf084

To be done
- 0 scattering distance in SSS will cause problems.
- 0 scattering distance doesn't coverage to diffuse color, this is generally not a problem, but not ideal. I would still like to get it fixed if possible. ( Cycles doesn't have this problem. )

**Comment by JiayinCao** [comment]
Done
- 0 scattering distance in SSS will cause problems.
- 0 scattering distance doesn't coverage to diffuse color, this is generally not a problem, but not ideal. I would still like to get it fixed if possible. ( Cycles doesn't have this problem. )

To be done
- Fixed the firefly problem.
- Figure out why there is a bias comparing with reference images generated by Cycles.

**Comment by JiayinCao** [comment]
Done
- Firefly problem is under control

Won't do
- There is still bias comparing with Cycles, which is more brighter. One of the reasons could be the different MIS pdf in BSSRDF evaluation. But there is others. However, due to the lack of sparetime, I would like to move forward to work on the next feature given that the BSSRDF in SORT is acceptable to me.

To be done
- Support multiple BSSRDF layers instead of just one.
- Fall back BSSRDF channel with zero radius to lamber for faster convergence rate.

**Comment by JiayinCao** [comment]
Done
- Support multiple BSSRDF layers instead of just one. e2f71be52defe1998cdaac8a1789ac910a66f7ee

To be done
- Fall back BSSRDF channel with zero radius to lamber for faster convergence rate.
- Better importance sampling algorithm inside scatteringevent, it should be weight-based.

**Comment by JiayinCao** [comment]
Done
- Fall back BSSRDF channel with zero radius to lamber for faster convergence rate. 17e6aa04099613c3faebd6ddf618567daac48904
- Better importance sampling algorithm inside scatteringevent, it should be weight-based. 82a7720862457e4ed937f667b887df68b87a163b

To be done
- Explore what is left. This feature is largely functional and almost done. But I would like to spend a little bit more time to polish it and fix the corner cases that I haven't thought of.
